config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end
  end
  resource :profile, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
    belongs_to :user
    has_many :tasks, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :task
end

app/models/profile.rb
class Profile < ApplicationRecord
    enum gender: { male: 0, female: 1, other: 2 }
    belongs_to :user
    has_one_attached :avatar
end

app/models/task.rb
class Task < ApplicationRecord
    has_one_attached :eyecatch

    has_many :comments, dependent: :destroy
    belongs_to :user
    belongs_to :board
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :profile, dependent: :destroy

  delegate :birthday, :age, :gender, to: :profile, allow_nil: true

  def prepare_profile
    profile || build_profile
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'avatar-john.png'
    end
  end

  def has_written(board)
    boards.exists?(id: board.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    before_action :set_board, only: [:show]
    def index
        @boards = Board.all
    end

    def show
        @tasks = @board.tasks
    end

    def new
        @board = current_user.boards.build
    end

    def create
        @board = current_user.boards.build(board_params)
        if @board.save
            redirect_to board_path(@board), notice: '保存しました'
        else
            flash.now[:error] = '保存できませんでした'
            render :new
        end
    end

    def edit
        @board = current_user.boards.find(params[:id])
    end

    def update
        @board = current_user.boards.find(params[:id])
        if @board.update(board_params)
            redirect_to board_path(@board), notice: '更新できました'
        else
            flash.now[:error] = '更新できませんでした'
            render :edit
        end
    end

    def destroy
        board = current_user.boards.find(params[:id])
        board.destroy!
        redirect_to root_path, notice: '削除に成功しました'
    end

    private
    def board_params

        params.require(:board).permit(:title, :description)

    end

    def set_board
        @board = Board.find(params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        board = Board.find(params[:board_id])
        @task = Task.find(params[:task_id])
        @comment = @task.comments.build
    end

    def create
        board = Board.find(params[:board_id])
        task = Task.find(params[:task_id])
        @comment = task.comments.build(comment_params)
        @comment.user_id = current_user.id
        if @comment.save!
            redirect_to board_task_path(board, task)
        else
            render :new
        end
    end

    private
    def comment_params
        params.require(:comment).permit(:comment)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!
    def show
        @profile = current_user.profile
    end

    def edit
        @profile = current_user.prepare_profile
    end

    def update
        @profile = current_user.prepare_profile
        @profile.assign_attributes(profile_params)
        if @profile.save
            redirect_to profile_path, notice: 'Updated Profile'
        else
            flash.now[:error] = 'Not Updated'
            render :edit
        end
    end

    private
    def profile_params
        params.require(:profile).permit(
            :nickname,
            :introduction,
            :gender,
            :birthday,
            :subscribed,
            :avatar
        )
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!

    def show
        @board = Board.find(params[:board_id])
        @task = @board.tasks.find(params[:id])
        @comments = @task.comments
    end

    def new
        @board = Board.find(params[:board_id])
        @task = @board.tasks.build
    end

    def create
        board = Board.find(params[:board_id])
        @task = board.tasks.build(task_params)
        @task.user_id = current_user.id
        if @task.save!
            redirect_to board_task_path(board, @task)
        else
            render :new
        end
    end

    def edit
        @board = Board.find(params[:board_id])
        @task = @board.tasks.find(params[:id])
    end

    def update
        @board = Board.find(params[:board_id])
        @task = @board.tasks.find(params[:id])
        if @task.update(task_params)
            redirect_to board_task_path(@board, @task)
        else
            render :edit
        end
    end

    def destroy
        # board = current_user.boards.find(params[:id])
        # board.destroy!
        # redirect_to root_path, notice: '削除に成功しました'
        board = Board.find(params[:board_id])
        task = board.tasks.find(params[:id])
        task.destroy!
        redirect_to board_path(board), notice: 'Successed!'
    end

    private
    def task_params
        params.require(:task).permit(:title, :description, :deadline, :eyecatch)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.haml
.container
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @board, local: true) do |f|
    %h2 New Board
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :description, 'Description'
    %div
      = f.text_area :description
    = f.submit 'Submit', class: 'btn-primary'

app/views/boards/edit.html.haml
= render 'form', board: @board

app/views/boards/index.html.haml
.container
    %h2 All Boards
    - @boards.each do |board|
        .board
            .frame
                = link_to board_path (board) do
                    .frame_top
                        .frame_title
                            = board.title
                        - if user_signed_in? && current_user.has_written(board)
                            .frame_edit
                                .dropdown
                                    = image_tag '3dots.svg', class: 'dropbtn'
                                .dropdown-content
                                    = link_to 'Edit', edit_board_path(board)
                                    = link_to 'Delete', board_path(board), class: 'delete', data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
                .frame_description
                    = board.description
                .frame_creater
                    = image_tag board.user.avatar_image
    .board-add
        %p + Add new board

            

app/views/boards/new.html.haml
.container
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @board, local: true) do |f|
    %h2 New Board
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :description, 'Description'
    %div
      = f.text_area :description
    = f.submit 'Submit', class: 'btn-primary'

app/views/boards/show.html.haml
.container
    %h2 Brackets
    - @tasks.each do |task|
        .board
            .frame
                = link_to board_task_path(@board, task) do
                    - if task.eyecatch.attached?
                        .frame_image
                            = image_tag task.eyecatch
                    .frame_top
                        .frame_title
                            = task.title
                .frame_description
                    = task.description
                .frame_creater
                    = image_tag task.user.avatar_image
    .board-add
        = link_to new_board_task_path(@board) do
            %p + Add new card

app/views/comments/new.html.haml
.container
  %ul
    - @comment.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @comment, local: true, url: board_task_comments_path) do |f|
    %h2 New Comment
    %div
      = f.text_area :comment
    = f.submit 'Submit', class: 'btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title ChatappTomojoz
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      %h1= link_to 'Chatapp', root_path
    = yield

app/views/profiles/edit.html.haml
.container
    %ul
        - @profile.errors.full_messages.each do |message|
            %li= message

    = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
        %div
            = f.label :avatar, 'アバター'
        %div
            = f.file_field :avatar
        %div
            = f.label :nickname, 'ハンドルネーム'
        %div
            = f.text_field :nickname, class: 'text'
        %div
            = f.label :introduction, '自己紹介'
        %div
            = f.text_area :introduction
        %div
            = f.label :gender, '性別'
        %div
            = f.select :gender, Profile.genders.map { |k, v| [ I18n.t("enum.genders.#{k}"), k ] }, {}, { class: 'text' }
        %div
            = f.label :birthday, '生年月日'
        %div
            = f.date_field :birthday, class: 'text'
        %div
            = f.label :subscribed, '通知を受け取る'
            = f.check_box :subscribed
        
        = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/edit.html.haml
.container
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message
  = form_with model: [@board, @task] do |f|
    %h2 New Card
    %div
      = f.label :eyecatch, 'アイキャッチ'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :description, 'Description'
    %div
      = f.text_area :description
    %div
      = f.label :deadline, 'Deadline'
    %div
      = f.date_field :deadline, class: 'text'
    = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/new.html.haml
.container
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message
   = form_with(model: @task, local: true, url: board_tasks_path) do |f|
    %h2 New Card
    %div
      = f.label :eyecatch, 'アイキャッチ'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :description, 'Description'
    %div
      = f.text_area :description
    %div
      = f.label :deadline, 'Deadline'
    %div
      = f.date_field :deadline, class: 'text'
    = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/show.html.haml
.container
    .top_task
        .task_title
            = @task.title
        .task_detail_actions 
            .task_edit
                = image_tag '3dots.svg', class: 'dropbtn'
                .task_edit_content
                    = link_to 'Edit', edit_board_task_path(@board, @task)
                    = link_to 'Dlete', board_task_path(@board, @task), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
    .task_deadline
        = @task.deadline
    - if @task.eyecatch.attached?
        .task_image
            = image_tag @task.eyecatch
    .task_description
        %p= @task.description
    %h2.comment_header Comment
    - @comments.each do |comment|
        .comment_row
            .comment_creater
                = image_tag comment.user.avatar_image
            .comment_content
                %p= comment.comment        
    .board-add
        = link_to '+ Add new comment', new_board_task_comment_path(@board,@task)